<a href="https://colab.research.google.com/github/Ganpat9829/Certificate/blob/main/Practical_2_18BCE069.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
data = pd.read_csv('/content/Iris.csv')

In [ ]:
data.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
data.groupby('Species').size()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [ ]:
I, O = train_test_split(data, test_size=0.4, stratify=data['Species'])
I_train = I[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
O_train = I['Species']
I_test = O[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
O_test = O['Species']

In [ ]:
print(I_train.shape, O_train.shape)
print(I_test.shape, O_test.shape)

(90, 4) (90,)
(60, 4) (60,)


In [ ]:
ClassiFier = KNeighborsClassifier()
ClassiFier.fit(I_train, O_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
Predictions = ClassiFier.predict(I_test)
print(Predictions)

['Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor']


In [ ]:
print(accuracy_score(O_test, Predictions))
print(confusion_matrix(O_test, Predictions))

0.9833333333333333
[[20  0  0]
 [ 0 20  0]
 [ 0  1 19]]


In [ ]:
# Colab library to upload files to notebook
from google.colab import files

# Install Kaggle library
!pip install -q kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json


{'kaggle.json': b'{"username":"parthjasani","key":"d914e0134925a8901891717679615257"}'}

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] ='/content/'

In [ ]:
!kaggle competitions download -c nyc-taxi-trip-duration

train.zip: Skipping, found more recently modified local copy (use --force to force download)
test.zip: Skipping, found more recently modified local copy (use --force to force download)
sample_submission.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
!unzip /content/train.zip

Archive:  /content/train.zip
  inflating: train.csv               


In [ ]:
import pandas as pd
d = pd.read_csv('train.csv')

In [ ]:
print(d)

                id  vendor_id  ... store_and_fwd_flag trip_duration
0        id2875421          2  ...                  N           455
1        id2377394          1  ...                  N           663
2        id3858529          2  ...                  N          2124
3        id3504673          2  ...                  N           429
4        id2181028          2  ...                  N           435
...            ...        ...  ...                ...           ...
1458639  id2376096          2  ...                  N           778
1458640  id1049543          1  ...                  N           655
1458641  id2304944          2  ...                  N           764
1458642  id2714485          1  ...                  N           373
1458643  id1209952          1  ...                  N           198

[1458644 rows x 11 columns]


In [ ]:
d.columns

Index(['id', 'vendor_id', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'store_and_fwd_flag',
       'trip_duration'],
      dtype='object')

In [ ]:
d.describe()

vendor_id  passenger_count  ...  dropoff_latitude  trip_duration
count  1.458644e+06     1.458644e+06  ...      1.458644e+06   1.458644e+06
mean   1.534950e+00     1.664530e+00  ...      4.075180e+01   9.594923e+02
std    4.987772e-01     1.314242e+00  ...      3.589056e-02   5.237432e+03
min    1.000000e+00     0.000000e+00  ...      3.218114e+01   1.000000e+00
25%    1.000000e+00     1.000000e+00  ...      4.073588e+01   3.970000e+02
50%    2.000000e+00     1.000000e+00  ...      4.075452e+01   6.620000e+02
75%    2.000000e+00     2.000000e+00  ...      4.076981e+01   1.075000e+03
max    2.000000e+00     9.000000e+00  ...      4.392103e+01   3.526282e+06

[8 rows x 7 columns]

In [ ]:
d.groupby('vendor_id').size()

vendor_id
1    678342
2    780302
dtype: int64

In [ ]:
d.groupby('store_and_fwd_flag').size()

store_and_fwd_flag
N    1450599
Y       8045
dtype: int64

In [ ]:
#print(d['trip_duration'])
c_1000 = 0
c_3000 = 0
c = 0
for i in d['trip_duration']:
  if(i>0 and i<=1500):
    c_1000 = c_1000 + 1
  elif(i>1500 and i<=3000):
    c_3000 = c_3000 + 1
  else:
    c = c + 1


print("Trip with trip duration between 0 to 1500 seconds:", c_1000)
print("Trip with trip duration between 1500 to 3000 seconds:", c_3000)
print("Trip with trip duration more than 3000 seconds:", c)

Trip with trip duration between 0 to 1500 seconds: 1278222
Trip with trip duration between 1500 to 3000 seconds: 156599
Trip with trip duration more than 3000 seconds: 23823


**Conclusion:**

From this practical, we understood the limitations of working with big data with respect to time, memory etc. We performed some data analysis like filter, mean, median, groupby etc on Iris and NYC Taxi Datasets. We also performed classification using K-Neighbour Classifier on Iris Dataset.